# Generated by Django 2.2.14 on 2022-05-14 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='government_Notificationsinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_title', models.CharField(max_length=100)),
                ('notify_body', models.CharField(max_length=200)),
                ('notify_by_whom', models.CharField(max_length=200)),
                ('notify_dates', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='mentorinfo',
            name='total_earnings_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentorinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usrinfo',
            name='total_earnings_by',
            field=models.CharField(max_length=100),
        ),
    ]
